GET http://localhost:8080/api/v1/business
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoic3VwZXJhZG1pbkB0d2VuZGVuby5jb20iLCJlbWFpbCI6InN1cGVyYWRtaW5AdHdlbmRlbm8uY29tIiwiZXhwIjoxNzExMTkyNjE3LCJzdWIiOiJzdXBlcmFkbWluQHR3ZW5kZW5vLmNvbSJ9.6VQSRCq8Zt_YzUHNHPfgs3B5TpYrGolUI2NprdfXYCw

###

POST http://localhost:8080/api/v1/business
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoic3VwZXJhZG1pbkB0d2VuZGVuby5jb20iLCJlbWFpbCI6InN1cGVyYWRtaW5AdHdlbmRlbm8uY29tIiwiZXhwIjoxNzExMTkyNjE3LCJzdWIiOiJzdXBlcmFkbWluQHR3ZW5kZW5vLmNvbSJ9.6VQSRCq8Zt_YzUHNHPfgs3B5TpYrGolUI2NprdfXYCw

{
  "name": "twendeno",
  "email": "superadmin@twendeno.com",
  "address": "centre ville",
  "city": "Pointe-Noire",
  "country": "Rep. Congo",
  "phone": "066666666"
}

###