POST http://localhost:8080/api/v1/sign-in
Content-Type: application/json

{
  "username": "jd@mail.com",
  "password": "P@SSword12345"
}

###


# SUPER ADMIN
POST http://localhost:8080/api/v1/sign-in
Content-Type: application/json

{
  "username": "superadmin@twendeno.com",
  "password": "password"
}

###


# ADMIN
POST http://localhost:8080/api/v1/sign-in
Content-Type: application/json

{
  "username": "admin@mail.com",
  "password": "P@SSword12345"
}

###


# TENANT
POST http://localhost:8080/api/v1/sign-in
Content-Type: application/json

{
  "username": "tenant@mail.com",
  "password": "P@SSword12345"
}

###


# DEV
POST http://localhost:8080/api/v1/sign-in
Content-Type: application/json

{
  "username": "dev@mail.com",
  "password": "P@SSword12345"
}

###


# DRIVER
POST http://localhost:8080/api/v1/sign-in
Content-Type: application/json

{
  "username": "driver@mail.com",
  "password": "P@SSword12345"
}

###