# User

POST http://localhost:8080/api/v1/sign-up
Content-Type: application/json

{
  "name": "John Doe",
  "email": "jd@mail.com",
  "password": "P@SSword12345",
  "role": {
    "name": "USER"
  }
}

###

# Admin

POST http://localhost:8080/api/v1/sign-up
Content-Type: application/json

{
  "name": "admin",
  "email": "admin@mail.com",
  "password": "P@SSword12345",
  "role": {
    "name": "ADMIN"
  }
}

###

# Tenant

POST http://localhost:8080/api/v1/sign-up
Content-Type: application/json

{
  "name": "tenant",
  "email": "tenant@mail.com",
  "password": "P@SSword12345",
  "role": {
    "name": "TENANT"
  }
}

###

# Dev

POST http://localhost:8080/api/v1/sign-up
Content-Type: application/json

{
  "name": "dev",
  "email": "dev@mail.com",
  "password": "P@SSword12345",
  "role": {
    "name": "DEV"
  }
}

###

# DRIVER

POST http://localhost:8080/api/v1/sign-up
Content-Type: application/json

{
  "name": "driver",
  "email": "driver@mail.com",
  "password": "P@SSword12345",
  "role": {
    "name": "DRIVER"
  }
}

###
