# Get all users

GET http://localhost:8080/api/v1/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoic3VwZXJhZG1pbkB0d2VuZGVuby5jb20iLCJlbWFpbCI6InN1cGVyYWRtaW5AdHdlbmRlbm8uY29tIiwiZXhwIjoxNzExNTUyNzQzLCJzdWIiOiJzdXBlcmFkbWluQHR3ZW5kZW5vLmNvbSJ9.aGI3DfWryQQKZ6Bn9ifzDzRe6nifP9-BiNaLeNJVqZA

###

# Get user by user uuid

GET http://localhost:8080/api/v1/users/92961335-a541-4ab6-b828-74b0139d9df6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MTEzNTk4MTQsInN1YiI6InN1cGVyYWRtaW5AdHdlbmRlbm8uY29tIiwibmFtZSI6InN1cGVyYWRtaW5AdHdlbmRlbm8uY29tIiwiZW1haWwiOiJzdXBlcmFkbWluQHR3ZW5kZW5vLmNvbSJ9.tOnelWMiMw0dSXUhSIbFC_hGz16CyihbFCc0iWzzR3k

###

# Update user by user uuid

PUT http://localhost:8080/api/v1/users/92961335-a541-4ab6-b828-74b0139d9df6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MTEzNTk4MTQsInN1YiI6InN1cGVyYWRtaW5AdHdlbmRlbm8uY29tIiwibmFtZSI6InN1cGVyYWRtaW5AdHdlbmRlbm8uY29tIiwiZW1haWwiOiJzdXBlcmFkbWluQHR3ZW5kZW5vLmNvbSJ9.tOnelWMiMw0dSXUhSIbFC_hGz16CyihbFCc0iWzzR3k

{
  "name": "Sup Ad"
}

###