GET http://localhost:8080/api/v1/user-business
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoic3VwZXJhZG1pbkB0d2VuZGVuby5jb20iLCJlbWFpbCI6InN1cGVyYWRtaW5AdHdlbmRlbm8uY29tIiwiZXhwIjoxNzExNTUxMDU3LCJzdWIiOiJzdXBlcmFkbWluQHR3ZW5kZW5vLmNvbSJ9.rUEI_3aiWXK0rkavPaM7N3H6q2oHjU9DoTiYUrSTsHk

###

POST http://localhost:8080/api/v1/user-business
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoic3VwZXJhZG1pbkB0d2VuZGVuby5jb20iLCJlbWFpbCI6InN1cGVyYWRtaW5AdHdlbmRlbm8uY29tIiwiZXhwIjoxNzExNTUxMDU3LCJzdWIiOiJzdXBlcmFkbWluQHR3ZW5kZW5vLmNvbSJ9.rUEI_3aiWXK0rkavPaM7N3H6q2oHjU9DoTiYUrSTsHk

{
  "username": "superadmin@twendeno.com",
  "businessName": "twendeno"
}

###