# Create user Licenses

POST http://localhost:8080/api/v1/user-licenses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoic3VwZXJhZG1pbkB0d2VuZGVuby5jb20iLCJlbWFpbCI6InN1cGVyYWRtaW5AdHdlbmRlbm8uY29tIiwiZXhwIjoxNzExMTE5ODU4LCJzdWIiOiJzdXBlcmFkbWluQHR3ZW5kZW5vLmNvbSJ9.SDOu-UPQObK4QPdZDBITl5HWcRJTWXcWfL-nPKYmttY

{
  "businessName": "twendeno",
  "licenseName": "pro"
}

###

# Get User Licenses

GET http://localhost:8080/api/v1/user-licenses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoic3VwZXJhZG1pbkB0d2VuZGVuby5jb20iLCJlbWFpbCI6InN1cGVyYWRtaW5AdHdlbmRlbm8uY29tIiwiZXhwIjoxNzExMTE5ODU4LCJzdWIiOiJzdXBlcmFkbWluQHR3ZW5kZW5vLmNvbSJ9.SDOu-UPQObK4QPdZDBITl5HWcRJTWXcWfL-nPKYmttY


###