# Spring Boot configuration
spring:
  profiles:
    active: dev

  # Security configuration
  security:
    user:
      name: ${ADMIN_USERNAME}
      password: ${ADMIN_PASSWORD}

  # Database configuration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  # JPA properties
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    # mail configuration
  mail:
    host: localhost
    port: 9025

# Server configuration
server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /api/v1

# Logging configuration
logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
        hibernate: DEBUG